# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxObservable' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxObservable
pod 'RxSwift', '~> 4.0'
pod 'RxCocoa', '~> 4.0’
  target 'RxObservableTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxObservableUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
