# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwiftExample_pilgs' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod "RxSwift"
pod "RxCocoa"
  # Pods for RxSwiftExample_pilgs

  target 'RxSwiftExample_pilgsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxSwiftExample_pilgsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
