# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ObservableAndTheBind.' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'RxSwift'
pod 'RxCocoa'
pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'
  # Pods for ObservableAndTheBind.

  target 'ObservableAndTheBind.Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ObservableAndTheBind.UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
