# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Multi-Thread-Network' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Multi-Thread-Network
pod 'Alamofire'
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'ObjectMapper'

  target 'Multi-Thread-NetworkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Multi-Thread-NetworkUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
